//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TryingStuffWeb.Service
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Song", Namespace="http://schemas.datacontract.org/2004/07/TryingStuffCommon.Model")]
    public partial class Song : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ANameField;
        
        private TryingStuffCommon.Model.Artist AuthorField;
        
        private string NameField;
        
        private int RatingField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AName
        {
            get
            {
                return this.ANameField;
            }
            set
            {
                this.ANameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public TryingStuffCommon.Model.Artist Author
        {
            get
            {
                return this.AuthorField;
            }
            set
            {
                this.AuthorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rating
        {
            get
            {
                return this.RatingField;
            }
            set
            {
                this.RatingField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Artist", Namespace="http://schemas.datacontract.org/2004/07/TryingStuffCommon.Model")]
    public partial class Artist : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string NameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rating", Namespace="http://schemas.datacontract.org/2004/07/TryingStuffCommon.Model")]
    public partial class Rating : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AuthorNameField;
        
        private int RateField;
        
        private string RatingByUserField;
        
        private int SongIdField;
        
        private string SongNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthorName
        {
            get
            {
                return this.AuthorNameField;
            }
            set
            {
                this.AuthorNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rate
        {
            get
            {
                return this.RateField;
            }
            set
            {
                this.RateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RatingByUser
        {
            get
            {
                return this.RatingByUserField;
            }
            set
            {
                this.RatingByUserField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SongId
        {
            get
            {
                return this.SongIdField;
            }
            set
            {
                this.SongIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SongName
        {
            get
            {
                return this.SongNameField;
            }
            set
            {
                this.SongNameField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IEntryPointService")]
public interface IEntryPointService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntryPointService/SaveSong", ReplyAction="http://tempuri.org/IEntryPointService/SaveSongResponse")]
    bool SaveSong(TryingStuffCommon.Model.Song s);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntryPointService/SaveSong", ReplyAction="http://tempuri.org/IEntryPointService/SaveSongResponse")]
    System.Threading.Tasks.Task<bool> SaveSongAsync(TryingStuffCommon.Model.Song s);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntryPointService/SaveArtist", ReplyAction="http://tempuri.org/IEntryPointService/SaveArtistResponse")]
    bool SaveArtist(TryingStuffCommon.Model.Artist a);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntryPointService/SaveArtist", ReplyAction="http://tempuri.org/IEntryPointService/SaveArtistResponse")]
    System.Threading.Tasks.Task<bool> SaveArtistAsync(TryingStuffCommon.Model.Artist a);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntryPointService/GetRatings", ReplyAction="http://tempuri.org/IEntryPointService/GetRatingsResponse")]
    TryingStuffCommon.Model.Rating[] GetRatings();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntryPointService/GetRatings", ReplyAction="http://tempuri.org/IEntryPointService/GetRatingsResponse")]
    System.Threading.Tasks.Task<TryingStuffCommon.Model.Rating[]> GetRatingsAsync();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntryPointService/SongsByPlace", ReplyAction="http://tempuri.org/IEntryPointService/SongsByPlaceResponse")]
    TryingStuffCommon.Model.Song[] SongsByPlace();
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEntryPointService/SongsByPlace", ReplyAction="http://tempuri.org/IEntryPointService/SongsByPlaceResponse")]
    System.Threading.Tasks.Task<TryingStuffCommon.Model.Song[]> SongsByPlaceAsync();
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IEntryPointServiceChannel : IEntryPointService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class EntryPointServiceClient : System.ServiceModel.ClientBase<IEntryPointService>, IEntryPointService
{
    
    public EntryPointServiceClient()
    {
    }
    
    public EntryPointServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public EntryPointServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EntryPointServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public EntryPointServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public bool SaveSong(TryingStuffCommon.Model.Song s)
    {
        return base.Channel.SaveSong(s);
    }
    
    public System.Threading.Tasks.Task<bool> SaveSongAsync(TryingStuffCommon.Model.Song s)
    {
        return base.Channel.SaveSongAsync(s);
    }
    
    public bool SaveArtist(TryingStuffCommon.Model.Artist a)
    {
        return base.Channel.SaveArtist(a);
    }
    
    public System.Threading.Tasks.Task<bool> SaveArtistAsync(TryingStuffCommon.Model.Artist a)
    {
        return base.Channel.SaveArtistAsync(a);
    }
    
    public TryingStuffCommon.Model.Rating[] GetRatings()
    {
        return base.Channel.GetRatings();
    }
    
    public System.Threading.Tasks.Task<TryingStuffCommon.Model.Rating[]> GetRatingsAsync()
    {
        return base.Channel.GetRatingsAsync();
    }
    
    public TryingStuffCommon.Model.Song[] SongsByPlace()
    {
        return base.Channel.SongsByPlace();
    }
    
    public System.Threading.Tasks.Task<TryingStuffCommon.Model.Song[]> SongsByPlaceAsync()
    {
        return base.Channel.SongsByPlaceAsync();
    }
}
